-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.salaries
(
    emp_no integer NOT NULL,
    salary integer NOT NULL,
    PRIMARY KEY (emp_no)
);

CREATE TABLE public.titles
(
    title_id character varying(10) NOT NULL,
    title character varying(30) NOT NULL,
    PRIMARY KEY (title_id)
);

CREATE TABLE public.departments
(
    dept_no character varying(10) NOT NULL,
    dept_name character varying(30) NOT NULL,
    PRIMARY KEY (dept_no)
);

CREATE TABLE public.dept_emp
(
    emp_no integer NOT NULL,
    dept_no character varying(10) NOT NULL
);

CREATE TABLE public.dept_manager
(
    dept_no character varying(10) NOT NULL,
    emp_no integer NOT NULL,
    PRIMARY KEY (emp_no)
);

CREATE TABLE public.employees
(
    emp_no integer NOT NULL,
    emp_title_id character varying(10) NOT NULL,
    birth_date date NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    sex character varying(2) NOT NULL,
    hire_date date NOT NULL,
    PRIMARY KEY (emp_no)
);

CREATE TABLE public.dept_manager_dept_emp
(
    dept_manager_dept_no character varying(10) NOT NULL,
    dept_emp_dept_no character varying(10) NOT NULL
);

ALTER TABLE public.salaries
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (emp_title_id)
    REFERENCES public.titles (title_id)
    NOT VALID;


ALTER TABLE public.dept_manager
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no)
    NOT VALID;


ALTER TABLE public.dept_manager_dept_emp
    ADD FOREIGN KEY (dept_manager_dept_no)
    REFERENCES public.dept_manager (dept_no)
    NOT VALID;


ALTER TABLE public.dept_manager_dept_emp
    ADD FOREIGN KEY (dept_emp_dept_no)
    REFERENCES public.dept_emp (dept_no)
    NOT VALID;


ALTER TABLE public.dept_emp
    ADD FOREIGN KEY (dept_no)
    REFERENCES public.departments (dept_no)
    NOT VALID;

END;